
CREATE TABLE MSG_TEXT(
TABLE_MSG_ID VARCHAR(32) NOT NULL,
ToUserName      VARCHAR(50) NOT NULL,
FromUserName    VARCHAR(128) NOT NULL,
CreateTime      TIMESTAMP NOT NULL,
MsgType VARCHAR(20) NOT NULL,
Content VARCHAR(500)  NULL,
MsgId   VARCHAR(128)  NULL,
CONTENT_TYPE    VARCHAR(4) NOT NULL
);
ALTER TABLE  MSG_TEXT ADD CONSTRAINT PK_MSG_TEXT PRIMARY KEY (TABLE_MSG_ID);


CREATE TABLE MSG_IMAGE(
TABLE_MSG_ID VARCHAR(32) NOT NULL,
ToUserName      VARCHAR(50) NOT NULL,
FromUserName    VARCHAR(128) NOT NULL,
CreateTime      TIMESTAMP NOT NULL,
MsgType VARCHAR(20) NOT NULL,
PicUrl  VARCHAR(500) NULL,
MediaId VARCHAR(128) NULL,
MsgId   VARCHAR(128) NULL,
CONTENT_TYPE    VARCHAR(4) NOT NULL
);
ALTER TABLE  MSG_IMAGE ADD CONSTRAINT PK_MSG_IMAGE PRIMARY KEY (TABLE_MSG_ID);


CREATE TABLE MSG_VOICE(
TABLE_MSG_ID VARCHAR(32) NOT NULL,
ToUserName      VARCHAR(50) NOT NULL,
FromUserName    VARCHAR(128) NOT NULL,
CreateTime      TIMESTAMP NOT NULL,
MsgType VARCHAR(20) NOT NULL,
MediaId VARCHAR(128) NULL,
Format  VARCHAR(10) NULL,
MsgID   VARCHAR(128) NULL,
CONTENT_TYPE    VARCHAR(4) NOT NULL
);
ALTER TABLE  MSG_VOICE ADD CONSTRAINT PK_MSG_VOICE PRIMARY KEY (TABLE_MSG_ID);


CREATE TABLE MSG_VIDEO(
TABLE_MSG_ID VARCHAR(32) NOT NULL,
ToUserName      VARCHAR(50) NOT NULL,
FromUserName    VARCHAR(128) NOT NULL,
CreateTime      TIMESTAMP NOT NULL,
MsgType VARCHAR(20) NOT NULL,
MediaId VARCHAR(128) NULL,
ThumbMediaId    VARCHAR(128) NULL,
MsgID   VARCHAR(128) NULL,
Title   VARCHAR(300) NULL,
Description     VARCHAR(300) NOT NULL
);
ALTER TABLE  MSG_VIDEO ADD CONSTRAINT PK_MSG_VIDEO PRIMARY KEY (TABLE_MSG_ID);


CREATE TABLE MSG_LOCATION(
TABLE_MSG_ID VARCHAR(32) NOT NULL,
ToUserName      VARCHAR(50) NOT NULL,
FromUserName    VARCHAR(128) NOT NULL,
CreateTime      TIMESTAMP NOT NULL,
MsgType VARCHAR(20) NOT NULL,
Location_X      Double NOT NULL,
Location_Y      Double NOT NULL,
Scale   Integer NOT NULL,
Label   VARCHAR(128) NULL,
MsgID   VARCHAR(128) NOT NULL
);
ALTER TABLE  MSG_LOCATION ADD CONSTRAINT PK_MSG_LOCATION PRIMARY KEY (TABLE_MSG_ID);


CREATE TABLE MSG_LINK(
TABLE_MSG_ID VARCHAR(32) NOT NULL,
ToUserName      VARCHAR(50) NOT NULL,
FromUserName    VARCHAR(128) NOT NULL,
CreateTime      TIMESTAMP NOT NULL,
MsgType VARCHAR(20) NOT NULL,
Title   VARCHAR(500) NULL,
Description     VARCHAR(500) NULL,
Url     VARCHAR(500) NULL,
MsgID   VARCHAR(128) NOT NULL
);
ALTER TABLE  MSG_LINK ADD CONSTRAINT PK_MSG_LINK PRIMARY KEY (TABLE_MSG_ID);


CREATE TABLE MSG_EVENT_SUBSCRIBE(
TABLE_MSG_ID VARCHAR(32) NOT NULL,
ToUserName      VARCHAR(50) NOT NULL,
FromUserName    VARCHAR(128) NOT NULL,
CreateTime      TIMESTAMP NOT NULL,
MsgType VARCHAR(20) NOT NULL,
Event   VARCHAR(15)NULL,
EventKey        VARCHAR(128)NULL,
Ticket  VARCHAR(128) NULL
);
ALTER TABLE  MSG_EVENT_SUBSCRIBE ADD CONSTRAINT PK_MSG_EVENT_SUBSCRIBE PRIMARY KEY (TABLE_MSG_ID);


CREATE TABLE MSG_EVENT_LOCALTION(
TABLE_MSG_ID VARCHAR(32) NOT NULL,
ToUserName      VARCHAR(50) NOT NULL,
FromUserName    VARCHAR(128) NOT NULL,
CreateTime      TIMESTAMP NOT NULL,
MsgType VARCHAR(20) NOT NULL,
Event   VARCHAR(15) NULL,
Latitude        Double NULL,
Longitude       Double NULL,
LOCATION_Precision      Double NULL
);
ALTER TABLE  MSG_EVENT_LOCALTION ADD CONSTRAINT PK_MSG_EVENT_LOCALTION PRIMARY KEY (TABLE_MSG_ID);


CREATE TABLE MSG_EVENT_CLICK(
TABLE_MSG_ID VARCHAR(32) NOT NULL,
ToUserName      VARCHAR(50) NOT NULL,
FromUserName    VARCHAR(128) NOT NULL,
CreateTime      TIMESTAMP NOT NULL,
MsgType VARCHAR(20) NOT NULL,
Event   VARCHAR(15) NULL,
EventKey        VARCHAR(128)  NULL
);
ALTER TABLE  MSG_EVENT_CLICK ADD CONSTRAINT PK_MSG_EVENT_CLICK PRIMARY KEY (TABLE_MSG_ID);


CREATE TABLE MSG_SEND_IMAGES(
TABLE_MSG_ID VARCHAR(32) NOT NULL,
ToUserName      VARCHAR(50) NOT NULL,
FromUserName    VARCHAR(128) NOT NULL,
CreateTime      TIMESTAMP NOT NULL,
MsgType VARCHAR(20) NOT NULL,
ArticleCount    VARCHAR(15) NULL,
Articles        VARCHAR(128) NULL,
Title   VARCHAR(300) NULL,
Description     VARCHAR(300) NULL,
PicUrl  VARCHAR(300) NULL,
Url     VARCHAR(300) NULL
);
ALTER TABLE  MSG_SEND_IMAGES ADD CONSTRAINT PK_MSG_SEND_IMAGES PRIMARY KEY (TABLE_MSG_ID);





