
/*SM_MODULE_CATEGORY*/
CREATE TABLE SM_MODULE_CATEGORY(
	MODULE_CATEGORY_KEY VARCHAR(10) NOT NULL,
	MODULE_CATEGORY_NAME VARCHAR(120) NOT NULL,
	SORT INTEGER,
	ICON VARCHAR(100),
	MENU_FLAG CHAR(1) 
);

ALTER TABLE SM_MODULE_CATEGORY ADD CONSTRAINT PK_MODULE_CATEGORY PRIMARY KEY (MODULE_CATEGORY_KEY);

/*SM_MODULE*/
CREATE TABLE SM_MODULE(
	MODULE_KEY VARCHAR(10) NOT NULL,
	MODULE_CATEGORY_KEY VARCHAR(10) NOT NULL,
	MODULE_NAME VARCHAR(120) NOT NULL,
	URL VARCHAR(255) NOT NULL,
	AUTH_KEY VARCHAR(20) NOT NULL,
	SORT INTEGER 
);

ALTER TABLE SM_MODULE ADD CONSTRAINT PK_MODULE PRIMARY KEY (MODULE_KEY);
ALTER TABLE SM_MODULE ADD CONSTRAINT FK_MODULE_CATEGORY FOREIGN KEY (`MODULE_CATEGORY_KEY`) REFERENCES `SM_MODULE_CATEGORY` (`MODULE_CATEGORY_KEY`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*SM_FUNCTION*/
CREATE TABLE SM_FUNCTION(
	FUNCTION_KEY VARCHAR(20) NOT NULL,
	MODULE_KEY VARCHAR(10) NOT NULL,
	FUNCTION_NAME VARCHAR(120) NOT NULL,
	AUTH_KEY VARCHAR(20) NOT NULL,
	SORT INTEGER 
);

ALTER TABLE SM_FUNCTION ADD CONSTRAINT PK_FUNCTION PRIMARY KEY (FUNCTION_KEY);
ALTER TABLE SM_FUNCTION ADD CONSTRAINT FK_FUNCTION_MODULE FOREIGN KEY (`MODULE_KEY`) REFERENCES `SM_MODULE` (`MODULE_KEY`) ON DELETE NO ACTION ON UPDATE NO ACTION;


