

CREATE TABLE sm_user(
user_id	VARCHAR(32)	,
User_name	VARCHAR(50)	NOT NULL,
User_pws	VARCHAR(50)	NOT NULL,
User_status	VARCHAR(2)	NOT NULL
);
ALTER TABLE sm_user ADD CONSTRAINT PK_USER PRIMARY KEY(user_id);

/*SM_ROLE*/
CREATE TABLE SM_ROLE(
	ROLE_ID VARCHAR(10) NOT NULL,
	ROLE_NAME VARCHAR(100) NOT NULL
);

ALTER TABLE SM_ROLE ADD CONSTRAINT PK_SM_ROLE PRIMARY KEY (ROLE_ID);

/*SM_ROLE_MODULE*/
CREATE TABLE SM_ROLE_MODULE(
	ROLE_ID VARCHAR(10) NOT NULL,
	MODULE_KEY VARCHAR(10) NOT NULL
);
ALTER TABLE SM_ROLE_MODULE ADD CONSTRAINT PK_ROLE_MODULE PRIMARY KEY (ROLE_ID,MODULE_KEY);
ALTER TABLE SM_ROLE_MODULE ADD CONSTRAINT FK_ROLEMOD_ROLE FOREIGN KEY (`ROLE_ID`) REFERENCES `SM_ROLE` (`ROLE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE SM_ROLE_MODULE ADD CONSTRAINT FK_ROLEMOD_MOD FOREIGN KEY (`MODULE_KEY`) REFERENCES `SM_MODULE` (`MODULE_KEY`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*SM_ROLE_FUNCTION*/
CREATE TABLE SM_ROLE_FUNCTION(
	ROLE_ID VARCHAR(10) NOT NULL,
	FUNCTION_KEY VARCHAR(20) NOT NULL
);
ALTER TABLE SM_ROLE_FUNCTION ADD CONSTRAINT PK_ROLE_FUNCTION PRIMARY KEY (ROLE_ID,FUNCTION_KEY);
ALTER TABLE SM_ROLE_FUNCTION ADD CONSTRAINT FK_ROLEFUNC_ROLE FOREIGN KEY (`ROLE_ID`) REFERENCES `SM_ROLE` (`ROLE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE SM_ROLE_FUNCTION ADD CONSTRAINT FK_ROLEFUNC_FUNC FOREIGN KEY (`FUNCTION_KEY`) REFERENCES `SM_FUNCTION` (`FUNCTION_KEY`) ON DELETE NO ACTION ON UPDATE NO ACTION;


/*SM_ROLE_USER*/
CREATE TABLE SM_ROLE_USER(
	ROLE_ID VARCHAR(10) NOT NULL,
	USER_ID VARCHAR(32) NOT NULL
);
ALTER TABLE SM_ROLE_USER ADD CONSTRAINT PK_ROLE_USER PRIMARY KEY (ROLE_ID,USER_ID);
ALTER TABLE SM_ROLE_USER ADD CONSTRAINT FK_ROLE FOREIGN KEY (`ROLE_ID`) REFERENCES `SM_ROLE` (`ROLE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE SM_ROLE_USER ADD CONSTRAINT FK_ROLE_USER FOREIGN KEY (`USER_ID`) REFERENCES `sm_user` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

