
CREATE TABLE WX_DEPARTMENT_USER(
	DU_ID	VARCHAR(32) NOT NULL,
	DEPARTMENT_ID VARCHAR(20) NOT NULL,
	OPEN_ID		VARCHAR(128) NOT NULL,
	ACCOUNT_ID		VARCHAR(128) NOT NULL
);
ALTER TABLE WX_DEPARTMENT_USER ADD CONSTRAINT PK_WX_DEPARTMENT_USER PRIMARY KEY (DU_ID);

CREATE TABLE SM_DEPARTMENT(
	DEPARTMENT_ID VARCHAR(20) NOT NULL,
	DEPARTMENT_NAME VARCHAR(50) NOT NULL
);
ALTER TABLE SM_DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID);

