
CREATE TABLE WX_DEPARTMENT_USER(
	DU_ID	VARCHAR(32) NOT NULL,
	DEPARTMENT_ID VARCHAR(20) NOT NULL,
	OPEN_ID		VARCHAR(128) NOT NULL,
	ACCOUNT_ID		VARCHAR(128) NOT NULL
);
ALTER TABLE WX_DEPARTMENT_USER ADD CONSTRAINT PK_WX_DEPARTMENT_USER PRIMARY KEY (DU_ID);

CREATE TABLE SM_DEPARTMENT(
	DEPARTMENT_ID VARCHAR(20) NOT NULL,
	DEPARTMENT_NAME VARCHAR(50) NOT NULL
);
ALTER TABLE SM_DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID);


CREATE TABLE WX_ANSWER(
	pk_id varchar(32) not null,
	answer_id varchar(30) not null,
	USER_ID VARCHAR(20) NOT NULL,
	DEPARTMENT_ID VARCHAR(20) NOT NULL,
	ANSWER VARCHAR(100) NOT NULL,
	CREATE_TIME TIMESTAMP
);
ALTER TABLE WX_ANSWER ADD CONSTRAINT PK_WX_ANSWER PRIMARY KEY (pk_id);
