
CREATE TABLE WX_USER_SCORE(
	SCORE_ID VARCHAR(32) NOT NULL,
	USER_ID VARCHAR(10) NOT NULL,
	USER_NAME VARCHAR(50) NOT NULL,
	DEPARTMENT_ID VARCHAR(10) NOT NULL,
	DEPARTMENT_NAME VARCHAR(100) NOT NULL,
	SCORE INTEGER
);
ALTER TABLE WX_USER_SCORE ADD CONSTRAINT PK_USER_SCORE PRIMARY KEY (SCORE_ID);
ALTER TABLE WX_DEPARTMENT_USER ADD USER_NAME VARCHAR(50);

ALTER TABLE WX_USER_SCORE ADD IS_VALID VARCHAR(1) NOT NULL;

CREATE TABLE WX_ACTIVE(
	ACTIVE_INDEX INTEGER NOT NULL,
	ACTIVE_NAME VARCHAR(100) NOT NULL,
	BEG_TIME	TIMESTAMP NOT NULL,
	END_TIME TIMESTAMP NOT NULL
);
ALTER TABLE WX_ACTIVE ADD CONSTRAINT PK_ACTIVE PRIMARY KEY (ACTIVE_INDEX);


CREATE TABLE WX_ACTIVE_SCORE(
	SCORE_ID VARCHAR(32) NOT NULL,
	OPEN_ID	VARCHAR(128) NOT NULL,
	ACTIVE_INDEX	INTEGER NOT NULL,
	DEPARTMENT_ID VARCHAR(20) NOT NULL,
	SCORE INTEGER NOT NULL,
	SCORE_TEXT VARCHAR(100) NOT NULL
);
ALTER TABLE WX_ACTIVE_SCORE ADD CONSTRAINT PK_ACTIVE_SCORE PRIMARY KEY (SCORE_ID);

ALTER TABLE WX_ACTIVE_SCORE ADD CREATE_TIME TIMESTAMP NOT NULL;

