
CREATE TABLE SM_DEPARTMENT_USER (
	USER_ID VARCHAR(10) NOT NULL,
	DEPARTMENT_ID VARCHAR(10) NOT NULL
);
ALTER TABLE SM_DEPARTMENT_USER ADD CONSTRAINT PK_SM_DEPARTMENT_USER PRIMARY KEY (USER_ID);
