
CREATE TABLE WX_USER_SCORE(
	SCORE_ID VARCHAR(32) NOT NULL,
	USER_ID VARCHAR(10) NOT NULL,
	USER_NAME VARCHAR(50) NOT NULL,
	DEPARTMENT_ID VARCHAR(10) NOT NULL,
	DEPARTMENT_NAME VARCHAR(100) NOT NULL,
	SCORE INTEGER
);
ALTER TABLE WX_USER_SCORE ADD CONSTRAINT PK_USER_SCORE PRIMARY KEY (SCORE_ID);
ALTER TABLE WX_DEPARTMENT_USER ADD USER_NAME VARCHAR(50);
