
INSERT INTO sm_module_category(MODULE_CATEGORY_KEY,MODULE_CATEGORY_NAME,SORT,ICON,MENU_FLAG)
	VALUES('DEPART','部门配置',3,'fa-table','N');
COMMIT;

INSERT INTO sm_module(module_key,module_category_key,module_name,url,auth_key,sort)
	VALUES('DEPART_CON','DEPART','配置','admin/depart/list/tk2y-kd92h.od','tk2y',1);
COMMIT;

INSERT INTO sm_function(function_key,module_key,FUNCTION_NAME,AUTH_KEY,sort)
	VALUES('NEW_DEPART_CONF','DEPART_CON','新建','kd92h',0);
COMMIT;

INSERT INTO SM_DEPARTMENT VALUE('1000001' , '系统部');
INSERT INTO SM_DEPARTMENT VALUE('1000002' , '综合部');
INSERT INTO SM_DEPARTMENT VALUE('1000003' , '决策');
INSERT INTO SM_DEPARTMENT VALUE('1000004' , '渠道与销售管理部');
INSERT INTO SM_DEPARTMENT VALUE('1000005' , '广赢卡团队');
INSERT INTO SM_DEPARTMENT VALUE('1000006' , '风险部');
INSERT INTO SM_DEPARTMENT VALUE('1000007' , '内审组');
INSERT INTO SM_DEPARTMENT VALUE('1000008' , '信贷审批部');
INSERT INTO SM_DEPARTMENT VALUE('1000009' , '市场部');
INSERT INTO SM_DEPARTMENT VALUE('1000010' , '运营部');
INSERT INTO SM_DEPARTMENT VALUE('1000011' , '亲访团队');
INSERT INTO SM_DEPARTMENT VALUE('1000012' , '直销发卡部');
INSERT INTO SM_DEPARTMENT VALUE('1000013' , '直销分期部');
INSERT INTO SM_DEPARTMENT VALUE('1000014' , '资产管理部');
INSERT INTO SM_DEPARTMENT VALUE('1000015' , '信审部');
